services:
    cas_user.remove:
        class: CAS\UserBundle\Service\remove
        arguments: [ "@doctrine.orm.entity_manager", "@fos_user.user_manager"]

    cas_user.password_changing:
            class: CAS\UserBundle\EventListener\ChangePasswordListener
            arguments: [ "@doctrine.orm.entity_manager" ]
            tags:
                - { name: kernel.event_subscriber }