<?php

namespace DnDRules\WeaponBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeaponDamageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponDamageRepository extends EntityRepository
{
}
