<?php

namespace CAS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function count() {
        return  $this->createQueryBuilder('u')
                     ->select('COUNT(u)')
                     ->getQuery()
                     ->getSingleScalarResult();
    }
}
