<?php

namespace DnDInstance\FightBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FightMonsterInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightMonsterInstanceRepository extends EntityRepository
{
}
