<?php

namespace DnDRules\ClassDnDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassSpecificityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassSpecificityRepository extends EntityRepository
{
}
