<?php

namespace DnDRules\ClassDnDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassDnDLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassDnDLevelRepository extends EntityRepository
{
}
