<?php

namespace DnDRules\ClassDnDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassDnDSortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassDnDSortRepository extends EntityRepository
{
}
