<?php

namespace DnDRules\MonsterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonsterAbilityInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterAbilityInstanceRepository extends EntityRepository
{
}
