<?php

namespace DnDRules\SortBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SortSchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortSchoolRepository extends EntityRepository
{
}
