# -- Game -- #
game_game_game_home:
    path:     /parties
    defaults: { _controller: GameGameBundle:Game:index }
    
game_game_game_view:
    path:     /partie/vue/{slug}
    defaults: { _controller: GameGameBundle:Game:view }
    requirements:
        slug:  \S{0,255}
    
game_game_game_edit:
    path:     /partie/editer/{id}
    defaults: { _controller: GameGameBundle:Game:edit, id: 0 }
    requirements:
        id:  \d+
    
game_game_game_delete:
    path:     /partie/supprimer/{id}
    defaults: { _controller: GameGameBundle:Game:delete }
    requirements:
        id:  \d+