# -- Race -- #
dndrules_race_race_home:
    path:     /races
    defaults: { _controller: DnDRulesRaceBundle:Race:index }

dndrules_race_race_insert:
    path:     /race/insertion
    defaults: { _controller: DnDRulesRaceBundle:Race:register }
    
dndrules_race_race_view:
    path:     /race/vue/{slug}
    defaults: { _controller: DnDRulesRaceBundle:Race:view }
    requirements:
        slug:  \S{0,255}
    
dndrules_race_race_edit:
    path:     /race/editer/{id}
    defaults: { _controller: DnDRulesRaceBundle:Race:edit }
    requirements:
        id:  \d+

dndrules_race_race_edit_st:
    path:     /race/editer/jets-de-sauvegarde/{id}
    defaults: { _controller: DnDRulesRaceBundle:RaceST:edit }
    requirements:
        id:  \d+

dndrules_race_race_edit_skill:
    path:     /race/editer/compétences/{id}
    defaults: { _controller: DnDRulesRaceBundle:RaceSkill:edit }
    requirements:
        id:  \d+

dndrules_race_race_edit_level:
    path:     /race/editer/niveaux/{id}
    defaults: { _controller: DnDRulesRaceBundle:RaceLevel:edit }
    requirements:
        id:  \d+

dndrules_race_race_delete:
    path:     /race/supprimer/{id}
    defaults: { _controller: DnDRulesRaceBundle:Race:delete }
    requirements:
        id:  \d+