services:
    dndrules_race.deleterace:
        class: DnDRules\RaceBundle\Service\deleteRace
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]

    dndrules_race.race:
        class: DnDRules\RaceBundle\Service\race
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]