<?php

namespace DnDRules\RaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaceLevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceLevelsRepository extends EntityRepository
{
}
