<?php

namespace DnDRules\RaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaceSTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceSTRepository extends EntityRepository
{
}
