<?php

namespace DnDInstance\WeaponBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeaponInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponInstanceRepository extends EntityRepository
{
}
