<?php

namespace DnDInstance\ArmorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArmorInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorInstanceRepository extends EntityRepository
{
}
