services:
    dndrules_weapon.weapontypeaction:
        class: DnDRules\WeaponBundle\Service\weaponTypeAction
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
        
    dndrules_weapon.weaponaction:
        class: DnDRules\WeaponBundle\Service\weaponAction
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]