<?php

namespace DnDInstance\EquipmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipmentInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentInstanceRepository extends EntityRepository
{
}
