pm_administration_home_index:
    path:     /
    defaults: { _controller: PMAdministrationBundle:Home:index }

pm_administration_maj_index:
    path:     /maj
    defaults: { _controller: PMAdministrationBundle:Maj:index }