<?php

namespace DnDInstance\MonsterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonsterInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterInstanceRepository extends EntityRepository
{
}
