dndinstance_monster_monster_instance:
    path:     /instance/monstre/generer/{id}
    defaults: { _controller: DnDInstanceMonsterBundle:Monster:instance }
    requirements:
        id:  \d+
        
dndinstance_monster_monster_edit:
    path:     /instance/monstre/editer/{id}
    defaults: { _controller: DnDInstanceMonsterBundle:Monster:edit }
    requirements:
        id:  \d+
        
dndinstance_monster_monster_delete:
    path:     /instance/monstre/supprimer/{id}
    defaults: { _controller: DnDInstanceMonsterBundle:Monster:delete }
    requirements:
        id:  \d+

dndinstance_monster_monster_list_forGame:
    path:     /instance/monstre/liste/{id}
    defaults: { _controller: DnDInstanceMonsterBundle:Monster:listForGame }
    requirements:
        id:  \d+