dndinstance_weapon_weapon_instanceforcharacter:
    path:     /instance/arme/ajouter/{id}
    defaults: { _controller: DnDInstanceWeaponBundle:Weapon:instanceForCharacter }
    requirements:
        id:  \S{0,255}

dndinstance_weapon_weapon_instance_remove_fromCharacter:
    path:     /instance/arme/supprimer/{characterUsed_id}/{instance_id}/{game_id}
    defaults: { _controller: DnDInstanceWeaponBundle:Weapon:removeCharacterFromInstance }
    requirements:
        characterUsed_id:  \d+
        instance_id:  \d+
        game_id:  \d+

dndinstance_weapon_weapon_instance_edit:
    path:     /instance/arme/modifier/{id}
    defaults: { _controller: DnDInstanceWeaponBundle:Weapon:editInstance }
    requirements:
        id:  \d+
