dndinstance_sort_sort_instance:
    path:     /instance/sort/ajouter/{id}
    defaults: { _controller: DnDInstanceSortBundle:Sort:instance }
    requirements:
        id:  \d+

dndinstance_sort_sort_remove:
    path:     /instance/sort/supprimer/{id_sortInstance}/{id_characterUsed}
    defaults: { _controller: DnDInstanceSortBundle:Sort:remove }
    requirements:
        id_sortInstance:  \d+
        id_characterUsed:  \d+