dndinstance_sort_sort_generateInstance:
    path:     /instance/sort/ajouter/{id}
    defaults: { _controller: DnDInstanceSortBundle:Sort:generateInstance }
    requirements:
        id:  \d+

dndinstance_sort_sort_removeInstance:
    path:     /instance/sort/supprimer/{id_sortInstance}/{id_characterUsed}
    defaults: { _controller: DnDInstanceSortBundle:Sort:removeInstance }
    requirements:
        id_sortInstance:  \d+
        id_characterUsed:  \d+