<?php

namespace PM\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiceEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiceEntityRepository extends EntityRepository
{
}
