services:
    dndrules_armor.armoraction:
        class: DnDRules\ArmorBundle\Service\armorAction
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]
    
    dndrules_armor.deletearmortype:
        class: DnDRules\ArmorBundle\Service\deleteArmorType
        arguments: [ "@doctrine.orm.entity_manager", "@security.context"]