# -- Gift -- #
dndrules_gift_gift_home:
    path:     /dons
    defaults: { _controller: DnDRulesGiftBundle:Gift:index }
    
dndrules_gift_gift_view:
    path:     /don/vue/{slug}
    defaults: { _controller: DnDRulesGiftBundle:Gift:view }
    requirements:
        slug:  \S{0,255}
    
dndrules_gift_gift_edit:
    path:     /don/editer/{id}
    defaults: { _controller: DnDRulesGiftBundle:Gift:edit, id: 0 }
    requirements:
        id:  \d+
    
dndrules_gift_gift_delete:
    path:     /don/supprimer/{id}
    defaults: { _controller: DnDRulesGiftBundle:Gift:delete }
    requirements:
        id:  \S{0,255}
