dndinstance_fight_fight_generate:
    path:     /combat/instance/generer/{id}
    defaults: { _controller: DnDInstanceFightBundle:Fight:generate }
    requirements:
        id:  \d+
        
dndinstance_fight_fight_listforgame:
    path:     /combat/instance/liste/{id}
    defaults: { _controller: DnDInstanceFightBundle:Fight:listForGame }
    requirements:
        id:  \d+
        
dndinstance_fight_fight_edit:
    path:     /combat/instance/editer/{id}
    defaults: { _controller: DnDInstanceFightBundle:Fight:edit }
    requirements:
        id:  \d+
        
dndinstance_fight_fight_delete:
    path:     /combat/instance/supprimer/{id}
    defaults: { _controller: DnDInstanceFightBundle:Fight:delete }
    requirements:
        id:  \d+
        
dndinstance_fight_edit_characterUsed:
    path:     /combat/instance/editer/personnage/{game_id}/{fightCharacterUsedInstance_id}
    defaults: { _controller: DnDInstanceFightBundle:FightCharacterUsed:edit }
    requirements:
        fightCharacterUsedInstance_id:  \d+
        game_slug:  \S{0,255}
