<?php

namespace DnDRules\ArmorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArmorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorTypeRepository extends EntityRepository
{
}
