<?php

namespace DnDInstance\SortBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SortInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortInstanceRepository extends EntityRepository
{
}
